-- Create a Database
CREATE DATABASE CompanyDB
USE CompanyDB

-- Create EMPLOYEE Table
CREATE TABLE EMP
(
	SSN INT PRIMARY KEY,
	DNum INT IDENTITY(1, 1),
	FName NVARCHAR(10) NOT NULL,
	LName NVARCHAR(10) NOT NULL,
	SVID INT,
	Gender NVARCHAR(1) NOT NULL,
	Birthday DATE
	FOREIGN KEY (SVID) REFERENCES EMP(SSN)
)

-- Create DEPARTMENT Table
CREATE TABLE DEPT 
( 
	DName NVARCHAR(20) NOT NULL,
	DNum INT PRIMARY KEY IDENTITY(1, 1),
	SSN INT,
	HiringDate DATE,
	FOREIGN KEY (SSN) REFERENCES EMP(SSN)
)

-- Create LOCATION Table
CREATE TABLE LOC
(
	DNum INT IDENTITY(1, 1),
	DLoc NVARCHAR(20) NOT NULL,
	PRIMARY KEY (DNum, DLOC),
	FOREIGN KEY (DNum) REFERENCES DEPT(DNum)
)


-- Create PROJECT Table
CREATE TABLE PROJECT
(
	PNum INT PRIMARY KEY,
	DNum INT,
	PName NVARCHAR(50) NOT NULL,
	CITY NVARCHAR(20) NOT NULL,
	LOC NVARCHAR(20) NOT NULL,
	FOREIGN KEY (DNum) REFERENCES DEPT(DNum)
)

-- Create Work Table
CREATE TABLE WORK
(
	SSN INT NOT NULL,
	PNum INT NOT NULL,
	Hrs INT NOT NULL,
	FOREIGN KEY (SSN) REFERENCES EMP(SSN),
	FOREIGN KEY(PNum) REFERENCES PROJECT(PNum)
)

-- Create DEPENDENT Table
CREATE TABLE DPNT
(
	SSN INT,
	DEPNTName NVARCHAR(50) NOT NULL,
	PRIMARY KEY(SSN, DEPNTName),
	Gender NVARCHAR(1),
	Birthday DATE,
	FOREIGN KEY (SSN) REFERENCES EMP(SSN)
)